sentence='Indeed , Brazi many Brazilians blame Bolivia and its president ,pres  Evo Morales , for much of the energy squeeze their country is beginning to feel , in the form of higher prices for natural gas and uncertainties about future supplies '
sentence='LEATHER TEXTILE TEXTILE RUBBER'
import re
# re.escape(pattern) 可以对字符串中所有可能被解释为正则运算符的字符进行转义的应用函数。
# 如果字符串很长且包含很多特殊技字符，而你又不想输入一大堆反斜杠，或者字符串来自于用户(比如通过raw_input函数获取输入的内容)，且要用作正则表达式的一部分的时候，可以使用这个函数。
print(re.escape('www.com.cn.'))
def multiple_replace(text, adict):
     # print(list(map(re.escape, adict)))
     #map(func,iter_obj)func对迭代对象的每个元素进行操作

     #就是构建了正则表达式
     rx = re.compile('|'.join(map(re.escape, adict)))
     # print('rx',rx)
     def one_xlat(match):
           # print('match:',match.group(0))
           return adict[match.group(0)]
     #参数是函数时的用法
     return rx.sub(one_xlat, text)
adict={
    "ABS": "丙烯腈—丁二烯—苯乙烯共聚物",
    "ACRYLONITRILE-BUTADIENE-STYRENE": "丙烯腈—丁二烯—苯乙烯共聚物",
    "ALLOY": "合金",
    "ALUMIN": "铝",
    "ALUMINIUM": "铝合金",
    "AR": "芳纶",
    "ARAMID": "芳纶",
    "BRASS": "铜",
    "BUTYL": "丁基合成橡胶",
    "CA": "醋酯纤维",
    "ACETATE": "醋酯纤维",
    "CALFLEATHER": "小牛皮",
    "CARBON": "碳纤维制品",
    "CLF": "含氯纤维",
    "POLYVINYL CHLORIDE": "含氯纤维",
    "CLY": "莱赛尔纤维",
    "LYOCELL": "莱赛尔纤维",
    "CMD": "莫代尔纤维",
    "MODAL": "莫代尔纤维",
    "CO": "棉",
    "COTTON": "棉",
    "COPPER": "铜",
    "COWLEATHER": "牛皮革",
    "CP": "CP 树脂",
    "CELLULOSE PROPIONATE": "CP 树脂",
    "CTA": "三醋酯纤维",
    "TRIACETATE": "三醋酯纤维",
    "CU": "铜氨纤维",
    "CUPRO": "铜氨纤维",
    "CV": "粘胶纤维",
    "RAYON": "粘胶纤维",
    "DOWN": "羽绒",
    "FEATHER": "羽毛",
    "DUCK DOWN": "鸭绒",
    "EL": "氨纶",
    "ELASTANE": "氨纶",
    "ED": "二烯类弹性纤维",
    "ELASTODIENE": "二烯类弹性纤维",
    "EOL": "弹性纤维",
    "LASTOL": "弹性纤维",
    "EP": "新型合成纤维",
    "EPOXY RESIN": "新型合成纤维",
    "EPE": "乙烯-聚乙烯共聚物",
    "ETHYLENE-POLYETHYLENE": "乙烯-聚乙烯共聚物",
    "EVA": "乙烯醋酸乙烯共聚物",
    "ETHYLENE VINYL ACETATE": "乙烯醋酸乙烯共聚物",
    "Extruded Natural RU": "天然橡胶",
    "EXTRUDED NATURAL RUBBER": "天然橡胶",
    "FOAM": "发泡塑料",
    "GLASSFIBER": "玻璃纤维制品",
    "GOATLEATHER": "羊皮革",
    "GOOSE DOWN": "鹅绒",
    "GU": "橡胶",
    "GUM": "橡胶",
    "HDPE": "高密度聚乙烯",
    "POLYETHYLENE, HIGH DENSITY": "高密度聚乙烯",
    "HEMP": "大麻",
    "IRON": "铁",
    "K-RESIN": "K-树脂",
    "LAMBLEATHER": "羊羔皮革",
    "LATEX": "乳胶",
    "LI": "亚麻",
    "LINEN": "亚麻",
    "LUREX": "金属镀膜纤维",
    "Metal": "合金",
    "METAL": "合金",
    "NEOPRENE": "合成橡胶",
    "Ni": "镍",
    "NICKEL": "镍",
    "OTHERS": "其他材料",
    "PA": "锦纶",
    "NYLON": "锦纶",
    "PAN": "腈纶",
    "ACRYLIC": "腈纶",
    "Paper": "新型再生纤维",
    "PAPER": "新型再生纤维",
    "PC": "聚碳酸酯",
    "POLYCARBONATE": "聚碳酸酯",
    "PE": "聚乙烯",
    "POLYETHYLENE": "聚乙烯",
    "PE (HD)": "乙纶",
    "HIGH DENSITY POLYETHYLENE": "乙纶",
    "PE (LD)": "乙纶",
    "LOW DENSITY POLYETHYLENE": "乙纶",
    "PES": "聚酯纤维",
    "POLYESTER": "聚酯纤维",
    "PET": "聚酯纤维",
    "POLYETHYLENE TEREPHTHALATE": "聚酯纤维",
    "PIGLEATHER": "猪皮革",
    "Plastic": "塑料",
    "POLYMER": "塑料",
    "PMMA": "PMMA",
    "POLYMETHYL METHAACYRLATE": "PMMA",
    "POE": "聚烯烃弹性体",
    "POLYOLYALTHA OLFIN": "聚烯烃弹性体",
    "POM (Polyacetal)": "聚甲醛",
    "POLYOXYMETHYLENE": "聚甲醛",
    "PP": "聚丙烯",
    "POLYPROPYLENE": "聚丙烯",
    "PS": "聚苯乙烯",
    "POLYSTYRENE": "聚苯乙烯",
    "PTFE": "含氟纤维",
    "POLYTETRAFLUOROETHYLENE": "含氟纤维",
    "PU": "聚氨酯",
    "POLYURETHANE": "PU合成革",
    "PU FOAM": "聚氨酯泡沫塑料",
    "POLYURETHANE FOAM": "聚氨酯泡沫塑料",
    "PVC": "聚氯乙烯",
    "POLYVINYL CHLORIDE (PVC)": "聚氯乙烯",
    "RA": "苎麻",
    "RAMIE": "苎麻",
    "REC. PA": "锦纶",
    "POLYAMID (RECYCLED)": "锦纶",
    "REC.PES": "聚酯纤维(再生聚酯)",
    "POLYESTER (RECYCLED)": "聚酯纤维(再生聚酯)",
    "Reflective Piping Tape": "反光滚边带",
    "REFLECTIVE PIPING TAPE": "反光滚边带",
    "Reflective Tape": "反光带",
    "REFLECTIVE TAPE": "反光带",
    "RU": "橡胶",
    "RUBBER": "橡胶",
    "RU Thread": "橡胶线",
    "RUBBER THREAD": "橡胶线",
    "SEBS": "聚乙烯",
    "STYRENE ETHYLENE BUTYLENE STYRENE BLOCK COPOLYMER": "聚乙烯",
    "SBR": "丁苯橡胶",
    "STYRENE-BUTADIENE RUBBER": "丁苯橡胶",
    "SHEEPLEATHER": "羊皮革",
    "SHEEPSKIN": "羊皮革",
    "SI": "硅胶",
    "SILICON": "硅胶",
    "SILK": "桑蚕丝",
    "SILVER": "金属纤维",
    "SOYBEAN": "新型合成纤维",
    "STAINLESS STEEL": "不锈钢",
    "STEEL": "钢",
    "TI": "钛",
    "TITANIUM": "钛",
    "TPE": "热塑性弹性体",
    "THERMOPLASTIC ELASTOMER": "热塑性弹性体",
    "TPR": "热塑橡胶",
    "THERMO PLASTIC RUBBER": "热塑橡胶",
    "TPU": "热塑性聚氨酯",
    "THERMOPLASTIC POLYURETHANE": "热塑性聚氨酯",
    "WL": "美洲驼毛",
    "LLAMA": "美洲驼毛",
    "WM": "马海毛",
    "MOHAIR": "马海毛",
    "WN": "兔毛",
    "RABBIT HAIR": "兔毛",
    "WO": "羊毛",
    "WOOL": "绵羊毛",
    "WP": "羊驼毛",
    "ALPACA WOOL": "羊驼毛",
    "WS": "山羊绒",
    "CASHMERE": "山羊绒",
    "WV": "纯绵羊毛",
    "PURE WOOL": "纯绵羊毛",
    "ZINC ALLOY": "锌合金",
    "ZN (Zinc)": "锌",
    "ZINC": "锌",
    "VIS": "粘胶纤维",
    "VISCOSE": "粘胶纤维",
    "nan": "锦纶/聚酯纤维/氨纶",
    "GREY GOOSE DOWN": "灰鹅绒",
    "KANGAROO LEATHER": "袋鼠皮",
    "NATURAL RUBBER LATEX": "天然橡胶",
    "PU COATING": "PU涂层",
    "WHITE GOOSE DOWN": "白鹅绒",
    "POLYESTER (PU BONDING)": "聚酯纤维（非纤维物质除外）",
    "COTTON & LATEX": "棉乳胶复合面料",
    "POLYESTER & ETHYLENE VINYL ACETATE": "聚酯纤维乙烯醋酸乙烯共聚物复合面料",
    "COATING": "涂层",
    "FOAM RUBBER & TEXTILE": "发泡橡胶及织物",
    "SPANDEX": "氨纶",
    "POLYESTER (COATING EXCLUDED)": "聚酯纤维（非纤维物质除外）",
    "SHEEPLEATHER WITH FUR": "翻毛羊皮",
    "POLY": "聚酯",
    "POLYOLEFIN FIBER (COATING EXCLUDED)": "聚烯烃纤维（非纤维物质除外)",
    "NYLON (COATING EXCLUDED)": "锦纶(非纤维物质除外)",
    "TEXTILE": "织物",
    "NYLON(ELASTANE EXCLUDED)": "锦纶(氨纶除外)",
    "WHITE DUCK DOWN": "白鸭绒",
    "GREY DUCK DOWN": "灰鸭绒",
    "POLYESTER(COATING INCLUDED)": "聚酯纤维(含非纤维物质)",
    "RABBIT WOOL": "兔毛",
    "NATURAL RUBBER": "天然橡胶",
    "EXPANDING FOAM-STYRENE BUTADIENE RUBBER": "发泡丁苯橡胶",
    "EXPANDING FOAMED-POLYURETHANE RUBBER": "聚氨酯海绵",
    "EXPANDING FOAMED-POLYETHYLENE": "发泡聚乙烯",
    "PUCOMPOSITECOATINGFORTHEPOLYESTERFIBER": "聚酯纤维PU复合涂层",
    "NEW REGENERATED FIBER": "新型再生纤维",
    "REGENERATED CELLULOSE FIBER": "再生纤维素纤维",
    "TENCEL": "莱赛尔纤维",
    "CONTAINING TRACE EL": "含微量氨纶",
    "POLYESTER(CONTAINING TRACE EL)": "聚酯纤维（含微量氨纶）",
    "NYLON(CONTAINING TRACE EL)": "锦纶（含微量氨纶）",
    "(MIXTURE)": "(混合面料)",
    "(TRACE OTHERS INCLUDED)": "(含微量其他纤维)",
    "ACRYLIC-1": "聚丙烯腈纤维",
    "MIXTURE OF GREY DUCK DOWN AND ACRYLIC": "灰鸭绒，聚丙烯腈纤维混合物",
    "MIXTURE OF WHITE DUCK DOWN AND ACRYLIC": "白鸭绒，聚丙烯腈纤维混合物",
    "PU (MIXTURE)": "PU合成革(混合面料)",
    "NEW NATURAL FIBER": "新型天然纤维",
    "(EXCEPT NON FIBROUS MATERIAL)": "（非纤维物质除外）",
    "PES(TRACE OTHERS INCLUDED)": "聚酯纤维（含微量其他纤维）",
    "POLYAMID": "锦纶",
    "TERYLENE": "聚酯纤维",
    "EPP": "发泡聚丙烯",
    "ALUMINUM": "铝锰镁合金",
    "POLYESTER FILM FIBER": "聚酯薄膜纤维",
    "ELASTIC FIBER": "弹性纤维",
    "CO(TRACE OTHERS INCLUDED)": "棉（含微量其他纤维）",
    "POLYESTER(CONTAINING CATION DYABLE POLYESTER)": "聚酯纤维（含有阳离子染料可染改性聚酯纤维）",
    "POLYESTER(CONTAINING POLYESTER FILM FIBE)": "聚酯纤维（含聚酯薄膜纤维）",
    "ANGORA RABBIT WOOL": "安哥拉兔毛",
    "SILICONE": "硅胶",
    "Transfer coating split leather": "剖层移膜革",
    "cow splitting leather": "牛皮二层革",
    "PCTG": "PCTG",
    "Reclaimed Leather": "再生革",
    "PU LEATHER": "聚氨酯合成革",
    "STAINLESS STEEL 06Cr19Ni10": "不锈钢06Cr19Ni10",
    "PES(glue included)": "聚酯纤维(含胶)",
    "STAINLESS STEEL 12Cr17Mn6Ni5N": "不锈钢12Cr17Mn6Ni5N",
    "RESIN": "树脂",
    "POLYURETHANE FIBER": "新型聚氨酯纤维",
    "ELASTIC RIBBON": "弹性织带",
    "SYNTHETIC LEATHER": "合成革"
}
print(multiple_replace(sentence,{'Braziss ':'Brazi-loc ','sspres ':'pres_s '}))
print(multiple_replace(sentence,adict))



# import re
# def dashrepl(matchobj):
#      print(matchobj.group())
#      if matchobj.group(0) == '-':
#            return '***'
#      else:
#            return '+++'
# print(re.sub('-{1,2}', dashrepl, 'pro-----gram---files'))
#
# print(re.sub(r'\sAND\s', ' & ', 'Baked Beans And Spam', flags=re.IGNORECASE))
# # 'Baked Beans & Spam')
#
# input_data='0:品牌类型1:出口享惠情况2:稀土元素的重量百分比,以[A]表示3:GTIN4:CAS'
# def fun(match):
#     #函数会被使用多次，匹配一次使用一次
#     # if match.group(0)=='1:':
#     #     return '1111'
#     # else :
#     #     return '0000'
#     return '{}_**'.format(match.group(0))
#
# print(re.sub('\d:',fun,input_data))